// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgupuwkryhbvbucsaoyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndXB1d2tyeWhidmJ1Y3Nhb3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjMwMzMsImV4cCI6MjA3MjEzOTAzM30.xLm0M6_XkwgZqhC3FFtaLIXiWk9_29iF8dzwGwQZZ5Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});